# -*- coding: utf-8 -*-
# -*- ruby -*-

require 'rubygems'
require 'hoe'
require 'rake/extensiontask'
require 'rbconfig'

LUNA_INCLUDE_DIR = ENV['LUNA_INCLUDE_DIR'] || '/usr/safenet/lunaclient/samples/include'
RUBY_PKCS11_DIR = File.expand_path('..')


SHARED_FILES = [
  'ext/pk11_struct_macros.h',
  'ext/pk11_const_macros.h',
  'ext/pk11_version.h',
  'ext/generate_structs.rb',
  'ext/generate_constants.rb',
]
GENERATED_FILES = [
  "ext/std_structs.rb"
]

CLEAN.include SHARED_FILES
CLEAN.include GENERATED_FILES
CLEAN.include 'lib/pkcs11_luna_ext.so'
CLEAN.include 'tmp'
CLEAN.include 'examples/output'

def pkcs11_version
  file = File.join(RUBY_PKCS11_DIR, 'ext/pk11_version.h')
  version_re = /VERSION += +([\"\'])([\d][\d\w\.]+)\1/
  File.read_utf(file)[version_re, 2]
end

hoe = Hoe.spec 'pkcs11_luna' do
  developer('SafeNet', 'support@safenet-inc.com')
  extra_deps << ['pkcs11', "= #{pkcs11_version}"]
  extra_dev_deps << ['yard', '~> 0.6']
  extra_dev_deps << ['rake-compiler', '~> 0.7']

  self.summary = 'SafeNet-Luna extensions for PKCS#11-Ruby'
  self.description = 'This module allows Ruby programs to use vendor extensions for SafeNet Luna.'
  self.version = pkcs11_version

  self.readme_file = 'README_LUNA.rdoc'
  self.history_file = '../History.txt'
  self.extra_rdoc_files << self.readme_file << 'ext/pk11l.c'
  spec_extras[:extensions] = 'ext/extconf.rb'
  spec_extras[:files] = File.read_utf("Manifest.txt").split(/\r?\n\r?/)
  spec_extras[:files] += SHARED_FILES + GENERATED_FILES
  spec_extras[:required_ruby_version] = '>= 2.2.0'
end

Rake::ExtensionTask.new('pkcs11_luna_ext', hoe.spec) do |ext|
  ext.ext_dir = 'ext'
  ext.cross_compile = true                # enable cross compilation (requires cross compile toolchain)
  ext.cross_platform = ['i386-mingw32']     # forces the Windows platform instead of the default one
  puts "LUNA_INCLUDE_DIR: #{LUNA_INCLUDE_DIR.inspect}"
  ext.config_options << "--with-luna-dir-include=\"#{LUNA_INCLUDE_DIR}\""
end

# Add shared file from base pkcs11 gem
SHARED_FILES.each do |filename|
  file filename => File.join(RUBY_PKCS11_DIR, filename) do |t|
    cp t.prerequisites.first, t.name, verbose: true
  end
  file 'ext/extconf.rb' => filename
end

file "ext/std_structs.rb" do |t|
  require "pkcs11"
  std_structs = PKCS11.constants.select{|c| PKCS11.const_get(c).respond_to?(:ancestors) && !(PKCS11.const_get(c).ancestors & [PKCS11::CStruct, PKCS11::CK_ATTRIBUTE]).empty? }

  File.write t.name, "PKCS11_STD_STRUCTS = #{std_structs.inspect}"
end

task doc_files:  'ext/pk11l_struct.doc'

# vim: syntax=ruby
