name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 3" # At 05:00 on Wednesday # https://crontab.guru/#0_5_*_*_3

jobs:
  job_test_gem:
    name: Test in source tree
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            ruby: "head"
          - os: windows
            ruby: "3.2"
          - os: ubuntu
            ruby: "head"
          - os: ubuntu
            ruby: "4.0"
          - os: ubuntu
            ruby: "3.0"
          - os: ubuntu
            ruby: "truffleruby"
          - os: macos
            ruby: "head"

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}      # passed to ruby/setup-ruby
          apt-get: "libnss3" # Ubuntu
          brew: "nss"     # macOS
          mingw: ""   # Windows mingw / mswin /ucrt

      - name: Download firefox on Windows
        if: ${{ matrix.os == 'windows' }}
        run: |
          remove-item "C:/Program Files/Mozilla Firefox" -recurse
          $(new-object net.webclient).DownloadFile('http://ftp.mozilla.org/pub/firefox/releases/68.3.0esr/win64/en-US/Firefox%20Setup%2068.3.0esr.exe', 'C:/firefox-setup.exe')
          "SOFTOKN_PATH=C:/Program Files/Mozilla Firefox/softokn3.dll" >> $env:GITHUB_ENV
          "RUBY_DLL_PATH=C:/Program Files/Mozilla Firefox" >> $env:GITHUB_ENV
          "C:/Program Files/Mozilla Firefox" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install firefox on Windows
        if: ${{ matrix.os == 'windows' }}
        shell: cmd
        run: |
          "C:/firefox-setup.exe" -ms
          dir "C:/Program Files/Mozilla Firefox"

      - name: Print tool versions
        run: |
          ruby -v
          gcc -v
          gem env

      - name: Bundle install
        run: bundle install

      - name: Compile extension
        run: bundle exec rake compile

      - name: Run tests
        run: bundle exec rake test

      - name: Build gem
        run: bundle exec rake gem

      - name: Print compile logs if failed
        if: ${{ failure() && matrix.os != 'windows' }}
        run: find . -name '*.log' -print0 | xargs -0 cat
